name: Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: 'KRYPTON - Pack No.36'
        path: |
          KRYPTON presets
          KRYPTON projects
          KRYPTON samples
          LICENSE
          !./**/*.md

